### ISSUE TITLE
Edge cannot be installed on Windows Server 2016

### ISSUE THREAD

**Issue by scraperg** [microsoft/DroneRescue#5]
I don't think the instructions in the README.md can be completed.

In Create an Azure Virtual Machine:
```
2. Click Create a resource then search for and select Windows Server 2016 VM
```

Later, in Create a Custom Vision Model:
```
1. Using Microsoft Edge, open the following URL in a browser and login using your MSA https://customvision.ai/
[!ALERT] Custom Vision doesn't support Internet Explorer.
```

But the VM only has IE installed. And, as far as I can tell, Edge cannot be installed on Windows Server 2016.

Thanks.

**Comment by PaulStubbs** [comment]
The new Chromium based Edge browser should work https://www.microsoftedgeinsider.com/en-us/
